<?php
/**
 * @file
 * Provides primary Drupal hook implementations.
 */

/**
 * Implements hook_permission().
 */
function awssdk3_permission() {
  return array(
    'access awssdk ui' => array(
      'title' => t('Access services configuration'),
      'description' => t('Perform administration tasks for AWS SDK for PHP.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function awssdk3_menu() {
  $items['admin/config/aws'] = array(
    'title' => 'Amazon web services',
    'description' => 'Amazon web services tools.',
    'position' => 'right',
    'access arguments' => array('access awssdk ui'),
    'page callback' => 'system_admin_menu_block_page',
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  return $items;
}

/**
 * Implements hook_ctools_plugin_type().
 */
function awssdk3_ctools_plugin_type() {
  $plugins['service'] = array(
    'load themes' => FALSE,
    'use hooks' => FALSE,
  );
  return $plugins;
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function awssdk3_ctools_plugin_directory($module, $plugin) {
  if ($module == 'awssdk3' && $plugin == 'service') {
    return 'plugins/awssdk';
  }
  if ($module == 'ctools' && $plugin == 'export_ui') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Returns the client for a service.
 *
 * @link http://docs.aws.amazon.com/aws-sdk-php/v2/api/class-Guzzle.Service.Builder.ServiceBuilder.html#_get
 *
 * @param string $service
 *    Shortname of a aws service.
 *
 * @return Guzzle\Service\ClientInterface
 *   ClientInterface object
 */
function awssdk3_get_client($service) {
  $client = &drupal_static(__FUNCTION__ . '-' . $service);
  if (empty($client)) {
    $default = awssdk3_service_load('default');
    $sdk = new Aws\Sdk($default->config);

    $service_conf = awssdk3_service_load($service);
    $client = $sdk->createClient($service, (array) $service_conf->config);
  }
  return $client;
}

/**
 * Loads the stored configuration of a service and fallbacks to the stored default settings.
 *
 * @param string $service
 *    Shortname of a aws service.
 *
 * @return object|NULL
 *   The object for the service or NULL when the service could not be loaded.
 */
function awssdk3_service_load($service = '') {
  ctools_include('export');
  $object = NULL;
  if (!empty($service)) {
    $object = ctools_export_load_object('awssdk_services', 'names', array($service));
  }
  return !empty($object) ? reset($object) : NULL;
}
